[platformio]
default_envs = room1_image_piano, room2_chess, room3_star_slider, room3_star_sky, room3_candle, room3_knocking, ctrl_maglock_ctrl
src_dir = src
include_dir = include
lib_dir = lib

[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_ldf_mode = chain+
monitor_filters = time, esp32_exception_decoder

lib_deps =
    arduino-libraries/Ethernet @ ^2.0.2
    knolleary/PubSubClient @ ^2.8
    bblanchon/ArduinoJson @ ^7.0.0

build_unflags = -std=gnu++11
build_flags =
    -I include
    -std=gnu++17
    -D ETH_SPI_SCK=18
    -D ETH_SPI_MISO=19
    -D ETH_SPI_MOSI=23
    -D ETH_CS=15
    -D ETH_RST=2
    -D HB_INTERVAL_MS=7000
    -D METRIC_INTERVAL_MS=60000

[env:room1_image_piano]
build_src_filter = +<room1_image_piano.cpp>
lib_deps =
    ${env.lib_deps}
    kosme/arduinoFFT @ ^1.6.2

[env:room2_chess]
build_src_filter = +<room2_chess.cpp>

[env:room3_star_slider]
build_src_filter = +<room3_star_slider.cpp>

[env:room3_star_sky]
build_src_filter = +<room3_star_sky.cpp>

[env:room3_candle]
build_src_filter = +<room3_candle.cpp>

[env:room3_knocking]
build_src_filter = +<room3_knocking.cpp>

[env:ctrl_maglock_ctrl]
build_src_filter = +<ctrl_maglock_ctrl.cpp>
