[platformio]
default_envs = room1_image_piano

[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
build_flags =
  -D ER_PROJECT="er1"
  -D ER_VERSION="0.1.0"
  -D W5500_SPI_SCK=18
  -D W5500_SPI_MISO=19
  -D W5500_SPI_MOSI=23
  -D W5500_SPI_CS=15
  -D W5500_RST=2
  -D HB_MS=7000
  -D METRIC_S=60
  -D TWDT_S=3
lib_deps =
  knolleary/PubSubClient @ ^2.8
  miguelbalboa/MFRC522 @ ^1.4.11
  DFRobot/DFRobotDFPlayerMini @ ^1.0.5

[env:room1_image_piano]
build_src_filter = +<src/room1_image_piano>

[env:room2_chess]
build_src_filter = +<src/room2_chess>

[env:room3_star_verify]
build_src_filter = +<src/room3_star_verify>

[env:room3_candle]
build_src_filter = +<src/room3_candle>

[env:room3_knocking]
build_src_filter = +<src/room3_knocking>

[env:ctrl_maglock_ctrl]
build_src_filter = +<src/ctrl_maglock_ctrl>
