; ===================== GLOBAL SETTINGS =====================
[platformio]
default_envs = room0_maglock_ctrl
src_dir      = src
include_dir  = include

; ===================== BASE ENV (SHARED) =====================
[env]
platform      = espressif32
board         = esp32dev
framework     = arduino
monitor_speed = 115200
upload_speed  = 115200

monitor_filters =
    esp32_exception_decoder
    time

build_unflags = -std=gnu++11

build_flags =
    -std=gnu++17
    -D ETH_SPI_HOST=VSPI
    -D ETH_MISO=19
    -D ETH_MOSI=23
    -D ETH_SCLK=18
    -D ETH_CS=15
    -D ETH_RST=27
    -D ETH_SPI_CLOCK_MHZ=20
    ; --- Common project flags ---
    -D PIO_FRAMEWORK_ARDUINO_LWIP2_LOW_MEMORY
    -D ARDUINOJSON_USE_LONG_LONG=1

lib_deps =
    arduino-libraries/Ethernet
    knolleary/PubSubClient
    bblanchon/ArduinoJson


; ===================== CONTROLLER – MAGLOCK =======================
[env:room0_maglock_ctrl]
extends           = env
build_src_filter  = +<room0_maglock_ctrl.cpp>

; ===================== ROOM 1 – PIANO / IMAGES ====================
[env:room1_images_piano]
extends           = env
build_src_filter  = +<room1_images_piano.cpp>
lib_deps =
    ${env.lib_deps}
    kosme/arduinoFFT

; ===================== ROOM 2 – CHESS  =======================
[env:room2_chess]
extends           = env
build_src_filter  = +<room2_chess.cpp>

; ===================== ROOM 2 – CHESS RFID =======================
[env:room2_chess_rfid]
extends           = env
build_src_filter  = +<room2_chess_rfid.cpp>
lib_deps =
    ${env.lib_deps}
    miguelbalboa/MFRC522

; ===================== ROOM 3 – STAR SLIDER LIGHTS ===============
[env:room3_star_slider]
extends           = env
build_src_filter  = +<room3_star_slider.cpp>

; ===================== ROOM 3 – STAR SKY VERIFY ==================
[env:room3_star_sky]
extends           = env
build_src_filter  = +<room3_star_sky.cpp>

; ===================== ROOM 3 – CANDLE (SOUND) ====================
[env:room3_candles]
extends           = env
build_src_filter  = +<room3_candles.cpp>

; ===================== ROOM 3 – KNOCKING ==========================
[env:room3_knocking]
extends           = env
build_src_filter  = +<room3_knocking.cpp>
lib_deps =
    ${env.lib_deps}
    dfrobot/DFRobotDFPlayerMini @ ^1.0.6

; ===================== ROOM 3 – STOP TIMER ========================
[env:room3_stop_timer]
extends           = env
build_src_filter  = +<room3_stop_timer.cpp>

