#!/usr/bin/env python3
# make_goertzel_table.py
#
# Usage:
#   python make_goertzel_table.py learned_key_freqs.csv --out_h key_table_goertzel.h
#
# Input CSV must have columns:
#   key,windows,f0_hz
# Optional row:
#   key == "SILENCE"  (used to export NOISE_TONE_HZ, and excluded from candidates)

import argparse
from pathlib import Path

import pandas as pd


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("csv_in", help="learned_key_freqs.csv")
    ap.add_argument("--out_h", default="key_table_goertzel.h", help="output header file")
    args = ap.parse_args()

    csv_in = Path(args.csv_in)
    out_h = Path(args.out_h)

    df = pd.read_csv(csv_in)

    # Basic validation
    for col in ("key", "f0_hz"):
        if col not in df.columns:
            raise SystemExit(f"Missing required column '{col}' in {csv_in}")

    df["key"] = df["key"].astype(str)

    # Extract SILENCE tone if present (used as a noise-reject reference)
    noise_tone_hz = 0.0
    sil = df[df["key"].str.upper() == "SILENCE"]
    if len(sil) > 0:
        noise_tone_hz = float(sil["f0_hz"].iloc[0])

    # Drop SILENCE from candidates
    df = df[df["key"].str.upper() != "SILENCE"].copy()

    # Drop obviously invalid freqs
    df = df[pd.to_numeric(df["f0_hz"], errors="coerce").notna()].copy()
    df["f0_hz"] = df["f0_hz"].astype(float)
    df = df[(df["f0_hz"] > 0.0) & (df["f0_hz"] < 20000.0)].copy()

    # Sort for readability
    df = df.sort_values("f0_hz", ascending=True)

    # Emit Arduino header
    out_h.parent.mkdir(parents=True, exist_ok=True)
    with out_h.open("w", encoding="utf-8") as f:
        f.write("// Auto-generated by make_goertzel_table.py\n")
        f.write("// Source: learned_key_freqs.csv (measured tuning)\n")
        f.write("#pragma once\n\n")
        f.write("typedef struct { const char* key; float f0; } key_f0_t;\n\n")
        f.write(f"static const float NOISE_TONE_HZ = {noise_tone_hz:.3f}f; // from SILENCE row (0 if absent)\n\n")
        f.write(f"static const int KEY_COUNT = {len(df)};\n")
        f.write("static const key_f0_t KEY_TABLE[] = {\n")
        for _, r in df.iterrows():
            key = r["key"].replace("\\", "\\\\").replace('"', '\\"')
            f0 = float(r["f0_hz"])
            f.write(f'  {{"{key}", {f0:.3f}f}},\n')
        f.write("};\n")

    print(f"Wrote: {out_h.resolve()}")
    if noise_tone_hz > 1.0:
        print(f"NOISE_TONE_HZ = {noise_tone_hz:.3f} Hz (from SILENCE row)")
    else:
        print("NOISE_TONE_HZ = 0.0 (no SILENCE row found)")
    print(f"KEY_COUNT = {len(df)}")


if __name__ == "__main__":
    main()
