param(
    [ValidateSet("maglock","images_piano","chess","knocking","candles","star_sky","star_slider","stop_timer")]
    [string]$Target,
    [string]$Env,
    [string]$Dev,
    [switch]$NoBuild
)

$scriptDir = Split-Path -Parent $PSCommandPath
Push-Location $scriptDir
try {

# ============ DEPLOYMENT MAP ============
$deployments = @{
    "maglock" = @{
        Env          = "maglock"
        Dev          = "maglock"
        CmdNode      = "maglock"
        FirmwareName = "maglock.bin"
        VerifyNodes  = @("maglock")
    }
    "images_piano" = @{
        Env          = "images_piano"
        Dev          = "images_piano"
        CmdNode      = "images_piano"
        FirmwareName = "images_piano.bin"
        VerifyNodes  = @("images_piano")
    }
    "chess" = @{
        Env          = "chess"
        Dev          = "chess"
        CmdNode      = "chess"
        FirmwareName = "chess.bin"
        VerifyNodes  = @("chess")
    }
    "knocking" = @{
        Env          = "knocking"
        Dev          = "knocking"
        CmdNode      = "knocking"
        FirmwareName = "knocking.bin"
        VerifyNodes  = @("knocking")
    }
    "candles" = @{
        Env          = "candles"
        Dev          = "candles"
        CmdNode      = "candles"
        FirmwareName = "candles.bin"
        VerifyNodes  = @("candles")
    }
    "star_sky" = @{
        Env          = "star_sky"
        Dev          = "star_sky"
        CmdNode      = "star_sky"
        FirmwareName = "star_sky.bin"
        VerifyNodes  = @("star_sky")
    }
    "star_slider" = @{
        Env          = "star_slider"
        Dev          = "star_slider"
        CmdNode      = "star_slider"
        FirmwareName = "star_slider.bin"
        VerifyNodes  = @("star_slider")
    }
    "stop_timer" = @{
        Env          = "stop_timer"
        Dev          = "stop_timer"
        CmdNode      = "stop_timer"
        FirmwareName = "stop_timer.bin"
        VerifyNodes  = @("stop_timer")
    }
}

function Get-FirmwareMainPath([string]$dev) {
    $p = Join-Path $scriptDir ("src/{0}_main.cpp" -f $dev)
    if (-not (Test-Path $p)) {
        # fallback: some devs may have different entry naming
        $p2 = Join-Path $scriptDir ("src/{0}.cpp" -f $dev)
        if (Test-Path $p2) { return $p2 }
        Write-Error "Unable to locate firmware main for '$dev'. Checked: $p and $p2"
        exit 1
    }
    return $p
}

function Get-FirmwareVersion([string]$dev) {
    $mainPath = Get-FirmwareMainPath $dev
    $content = Get-Content -Path $mainPath -Raw
    $match = [regex]::Match($content, 'FW_VERSION\s*=\s*"([^"]+)"')
    if (-not $match.Success) {
        Write-Error "Unable to locate FW_VERSION in $mainPath"
        exit 1
    }
    return $match.Groups[1].Value
}

function Get-FirmwareBuildSeed([string]$Override) {
    if ($Override) { return $Override }
    # Avoid spaces so the value survives header embedding cleanly.
    return (Get-Date).ToString("yyyy-MM-dd_HHmmss")
}

function Get-FirmwareBuildId([string]$Seed) {
    # Produce a deterministic 20-char base32-ish id from the seed string.
    # Stable + short + human-readable.
    $bytes = [System.Text.Encoding]::ASCII.GetBytes($Seed)
    $sha = [System.Security.Cryptography.SHA256]::Create()
    $hash = $sha.ComputeHash($bytes)

    $alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZ234567"
    $out = New-Object System.Text.StringBuilder
    for ($i=0; $i -lt 20; $i++) {
        $b = $hash[$i]
        $out.Append($alphabet[ $b % $alphabet.Length ]) | Out-Null
    }
    return $out.ToString()
}

function Write-FwBuildMetaHeader {
    param(
        [Parameter(Mandatory=$true)][string]$RepoRoot,
        [Parameter(Mandatory=$true)][string]$Build,
        [Parameter(Mandatory=$true)][string]$Seed
    )
    $metaPath = Join-Path $RepoRoot "src/fw_build_meta.h"

    # NOTE:
    # We write the per-run build string into a tiny header that is ONLY included from src/fw_build_id.cpp.
    # This keeps PlatformIO build_flags stable, so incremental builds stay fast (only fw_build_id.cpp recompiles).
    $content = @"
#pragma once
// Auto-generated by er1/firmware/ota.ps1. Do not edit by hand.
#define FW_BUILD_ID_STR `"$Build`"
#define FW_BUILD_SEED_STR `"$Seed`"
"@

    Set-Content -Path $metaPath -Value $content -Encoding ASCII
}

# ============ TARGET RESOLUTION ============
if (-not $Target) {
    Write-Error "Usage: .\ota.ps1 -Target <dev>  (valid: $($deployments.Keys -join ', '))"
    exit 1
}

$cfg = $deployments[$Target]
if (-not $cfg) {
    Write-Error "Unknown target: $Target"
    exit 1
}

if (-not $Env) { $Env = $cfg.Env }
if (-not $Dev) { $Dev = $cfg.Dev }

$cmdNode = $cfg.CmdNode
$firmwareName = $cfg.FirmwareName
$verifyNodes = $cfg.VerifyNodes

Write-Host "== TARGET = $Target  Env=$Env  Dev=$Dev  CmdNode=$cmdNode  Firmware=$firmwareName  VerifyNodes=$($verifyNodes -join ',') =="

$otaVersion = Get-FirmwareVersion $Dev
if (-not $otaVersion) {
    Write-Error "Failed to determine firmware version for $Dev"
    exit 1
}

# Build seed/id for verification + for embedding into firmware via src/fw_build_meta.h
$buildSeed = Get-FirmwareBuildSeed $null
$otaBuild = Get-FirmwareBuildId $buildSeed
Write-FwBuildMetaHeader -RepoRoot $scriptDir -Build $otaBuild -Seed $buildSeed

Write-Host "== Version = $otaVersion  Build=$otaBuild  Seed='$buildSeed'  =="

# ============ BUILD ============
$pio = "$HOME\.platformio\penv\Scripts\platformio.exe"
if (-not (Test-Path $pio)) {
    $pio = "platformio"
}

Write-Host "== Using PlatformIO: $pio =="

if (-not $NoBuild) {
    Write-Host "== Building environment '$Env' =="
    & $pio run --environment $Env
    if ($LASTEXITCODE -ne 0) {
        Write-Error "Build failed"
        exit 1
    }
}

Write-Host "== Build = $otaBuild =="

$firmwarePath = ".pio/build/$Env/firmware.bin"
Write-Host "== Preflight: verifying firmware exists at $firmwarePath =="
if (-not (Test-Path $firmwarePath)) {
    Write-Error "Firmware not found: $firmwarePath"
    exit 1
}

# ============ PI / MQTT CONFIG ============
$piHost = "192.168.0.10"
$piUser = "rudyy"
$piFirmwareDir = "/home/rudyy/er1/node_firmware"
$httpHost = "192.168.0.10"

# ============ SCP UPLOAD ============
Write-Host "== Uploading firmware to Pi as $firmwareName =="

ssh "$piUser@$piHost" "mkdir -p $piFirmwareDir"
if ($LASTEXITCODE -ne 0) {
    Write-Error "Failed to create firmware directory on Pi at $piFirmwareDir"
    exit 1
}

$remotePath = "$piUser@${piHost}:$piFirmwareDir/$firmwareName"
scp $firmwarePath $remotePath
if ($LASTEXITCODE -ne 0) {
    Write-Error "SCP failed"
    exit 1
}

# Verify URL from Pi (basic reachability)
$url = "http://$httpHost/node_firmware/$firmwareName"
Write-Host "== Verifying OTA URL from Pi: $url =="
ssh "$piUser@$piHost" "bash -lc 'curl -fsS -o /dev/null --max-time 3 `"$url`"'"
if ($LASTEXITCODE -ne 0) {
    Write-Error "Pi could not reach firmware URL: $url"
    exit 1
}

# ============ INVOKE PI PUBLISHER ============
Write-Host "== Triggering OTA on $cmdNode/cmd =="

$remotePublisher = "/home/rudyy/er1/scripts/ota_publish.py"
$publisherCmd = @"
bash -lc 'python3 $remotePublisher --dev "$Dev" --cmd-node "$cmdNode" --http-host "$httpHost" --version "$otaVersion" --build "$otaBuild" --target "$Dev" --firmware-name "$firmwareName"'
"@

# Run publisher on Pi
$publisherOut = ssh "$piUser@$piHost" $publisherCmd
if ($LASTEXITCODE -ne 0) {
    Write-Error "ota_publish.py failed"
    Write-Host $publisherOut
    exit 1
}

# Re-print parseable lines for the profile wrapper
# (keep these exact labels; er1_profile.ps1 parses them)
Write-Host "Firmware : $piFirmwareDir/$firmwareName"
Write-Host "URL      : $url"
Write-Host "Dev      : $Dev"
Write-Host "Version  : $otaVersion"
Write-Host "Build    : $otaBuild"
Write-Host "Target   : $Dev"
Write-Host "CmdNode  : $cmdNode"
Write-Host "CmdTopic : $cmdNode/cmd"

Write-Host "== DONE. Device will update. =="

} finally {
    Pop-Location
}
