param(
    [ValidateSet("maglock","images_piano","chess","knocking","candles","star_sky","star_slider","stop_timer")]
    [string]$Target,
    [string]$Env,
    [string]$Dev,
    [switch]$NoBuild
)

$scriptDir = Split-Path -Parent $PSCommandPath
Push-Location $scriptDir
try {

# =====================
# DEPLOYMENT MAP
# =====================
$deployments = @{
    "maglock" = @{ Env="maglock"; Dev="maglock"; CmdNode="maglock"; FirmwareName="maglock.bin"; VerifyNodes=@("maglock") }
    "images_piano" = @{ Env="images_piano"; Dev="images_piano"; CmdNode="images_piano"; FirmwareName="images_piano.bin"; VerifyNodes=@("images_piano") }
    "chess" = @{ Env="chess"; Dev="chess"; CmdNode="chess"; FirmwareName="chess.bin"; VerifyNodes=@("chess") }
    "knocking" = @{ Env="knocking"; Dev="knocking"; CmdNode="knocking"; FirmwareName="knocking.bin"; VerifyNodes=@("knocking") }
    "candles" = @{ Env="candles"; Dev="candles"; CmdNode="candles"; FirmwareName="candles.bin"; VerifyNodes=@("candles") }
    "star_sky" = @{ Env="star_sky"; Dev="star_sky"; CmdNode="star_sky"; FirmwareName="star_sky.bin"; VerifyNodes=@("star_sky") }
    "star_slider" = @{ Env="star_slider"; Dev="star_slider"; CmdNode="star_slider"; FirmwareName="star_slider.bin"; VerifyNodes=@("star_slider") }
    "stop_timer" = @{ Env="stop_timer"; Dev="stop_timer"; CmdNode="stop_timer"; FirmwareName="stop_timer.bin"; VerifyNodes=@("stop_timer") }
}

function Get-FirmwareMainPath([string]$dev) {
    $p = Join-Path $scriptDir ("src/{0}_main.cpp" -f $dev)
    if (-not (Test-Path $p)) {
        $p2 = Join-Path $scriptDir ("src/{0}.cpp" -f $dev)
        if (Test-Path $p2) { return $p2 }
        throw "Unable to locate firmware main for '$dev'. Checked: $p and $p2"
    }
    return $p
}

function Get-FirmwareVersion([string]$dev) {
    $mainPath = Get-FirmwareMainPath $dev
    $content = Get-Content -Path $mainPath -Raw
    $match = [regex]::Match($content, 'FW_VERSION\s*=\s*"([^"]+)"')
    if (-not $match.Success) { throw "Unable to locate FW_VERSION in $mainPath" }
    return $match.Groups[1].Value
}

function Get-FirmwareBuildSeed([string]$Override) {
    if ($Override) { return $Override }
    return (Get-Date).ToString("yyyy-MM-dd_HHmmss")
}

function Get-FirmwareBuildId([string]$Seed) {
    $bytes = [System.Text.Encoding]::ASCII.GetBytes($Seed)
    $sha = [System.Security.Cryptography.SHA256]::Create()
    $hash = $sha.ComputeHash($bytes)
    $alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZ234567"
    $out = New-Object System.Text.StringBuilder
    for ($i=0; $i -lt 20; $i++) {
        $b = $hash[$i]
        [void]$out.Append($alphabet[ $b % $alphabet.Length ])
    }
    return $out.ToString()
}

function Write-FwBuildMetaHeader {
    param(
        [Parameter(Mandatory=$true)][string]$RepoRoot,
        [Parameter(Mandatory=$true)][string]$Build,
        [Parameter(Mandatory=$true)][string]$Seed
    )
    $metaPath = Join-Path $RepoRoot "src/fw_build_meta.h"
    $hdr = @"
#pragma once
// Auto-generated by er1/firmware/ota.ps1. Do not edit by hand.
#define FW_BUILD_ID_STR `"$Build`"
#define FW_BUILD_SEED_STR `"$Seed`"
"@
    Set-Content -Path $metaPath -Value $hdr -Encoding ASCII
}

# Real timeout runner; keeps tool output visible (scp progress)
function Invoke-ExeWithTimeout {
    param(
        [Parameter(Mandatory=$true)][string]$FilePath,
        [Parameter(Mandatory=$true)][string[]]$ArgumentList,
        [int]$TimeoutSec = 60,
        [string]$What = "process"
    )

    # Use Start-Process for reliable scp/ssh behavior on Windows (avoids occasional hangs with ProcessStartInfo)
    $p = Start-Process -FilePath $FilePath -ArgumentList $ArgumentList -NoNewWindow -PassThru

    $deadline = (Get-Date).AddSeconds($TimeoutSec)
    while (-not $p.HasExited) {
        Start-Sleep -Milliseconds 100
        if ((Get-Date) -gt $deadline) {
            try { Stop-Process -Id $p.Id -Force } catch {}
            throw "$What timed out after ${TimeoutSec}s"
        }
    }

    if ($p.ExitCode -ne 0) {
        throw "$What failed (exit $($p.ExitCode))"
    }
}


function Invoke-SshCapture {
    param(
        [Parameter(Mandatory=$true)][string[]]$SshArgs,
        [Parameter(Mandatory=$true)][string]$HostSpec,
        [Parameter(Mandatory=$true)][string]$RemoteCommand
    )
    $out = & ssh @SshArgs $HostSpec $RemoteCommand 2>&1
    return ($out | Out-String)
}

# =====================
# TARGET RESOLUTION
# =====================
if (-not $Target) { throw "Usage: .\ota.ps1 -Target <dev> (valid: $($deployments.Keys -join ', '))" }
$cfg = $deployments[$Target]
if (-not $cfg) { throw "Unknown target: $Target" }

if (-not $Env) { $Env = $cfg.Env }
if (-not $Dev) { $Dev = $cfg.Dev }

$cmdNode      = $cfg.CmdNode
$firmwareName = $cfg.FirmwareName
$verifyNodes  = $cfg.VerifyNodes

Write-Host "== TARGET = $Target  Env=$Env  Dev=$Dev  CmdNode=$cmdNode  Firmware=$firmwareName  VerifyNodes=$($verifyNodes -join ',') =="

$otaVersion = Get-FirmwareVersion $Dev
$buildSeed  = Get-FirmwareBuildSeed $null
$otaBuild   = Get-FirmwareBuildId $buildSeed
Write-FwBuildMetaHeader -RepoRoot $scriptDir -Build $otaBuild -Seed $buildSeed

Write-Host "== Version = $otaVersion  Build=$otaBuild  Seed='$buildSeed'  =="

# =====================
# BUILD
# =====================
$pio = "$HOME\.platformio\penv\Scripts\platformio.exe"
if (-not (Test-Path $pio)) { $pio = "platformio" }
Write-Host "== Using PlatformIO: $pio =="

if (-not $NoBuild) {
    Write-Host "== Building environment '$Env' =="
    & $pio run --environment $Env
    if ($LASTEXITCODE -ne 0) { throw "Build failed" }
}

Write-Host "== Build = $otaBuild =="

# IMPORTANT: absolute firmware path so scp never breaks on cwd
$firmwarePathRel = Join-Path $scriptDir (".pio/build/{0}/firmware.bin" -f $Env)
Write-Host "== Preflight: verifying firmware exists at $firmwarePathRel =="
if (-not (Test-Path $firmwarePathRel)) { throw "Firmware not found: $firmwarePathRel" }
$firmwarePath = (Resolve-Path $firmwarePathRel).Path

# =====================
# PI / HTTP CONFIG
# =====================
$piHost = "192.168.0.10"
$piUser = "rudyy"
$piFirmwareDir = "/home/rudyy/er1/node_firmware"
$httpHost = "192.168.0.10"

$sshBaseArgs = @(
    "-o","BatchMode=yes",
    "-o","ConnectTimeout=5",
    "-o","ServerAliveInterval=2",
    "-o","ServerAliveCountMax=4"
)

# =====================
# UPLOAD
# =====================
$fwSize = (Get-Item $firmwarePath).Length
Write-Host ("== Uploading firmware to Pi as {0}  ({1} bytes) ==" -f $firmwareName, $fwSize)

& ssh @sshBaseArgs "$piUser@$piHost" "mkdir -p '$piFirmwareDir'"
if ($LASTEXITCODE -ne 0) { throw "Failed to create firmware directory on Pi at $piFirmwareDir" }

$remotePath = "$piUser@${piHost}:$piFirmwareDir/$firmwareName"
$scpArgs = @("-C") + $sshBaseArgs + @($firmwarePath, $remotePath)
$sw = [System.Diagnostics.Stopwatch]::StartNew()
Invoke-ExeWithTimeout -FilePath "scp" -ArgumentList $scpArgs -TimeoutSec 60 -What "SCP upload"
$sw.Stop()
Write-Host ("== Upload finished in {0:n2}s ==" -f $sw.Elapsed.TotalSeconds)

# =====================
# URL CHECK + SHA CHECK
# =====================
$url = ("http://{0}/node_firmware/{1}" -f $httpHost, $firmwareName).Trim()
Write-Host "== Verifying OTA URL from Pi: $url =="

& ssh @sshBaseArgs "$piUser@$piHost" "curl -fsS -o /dev/null --connect-timeout 3 --max-time 6 '$url'"
if ($LASTEXITCODE -ne 0) { throw "Pi could not reach firmware URL: $url" }

Write-Host "== Verifying HTTP-served firmware matches uploaded file (sha256) =="

$remoteFile = "$piFirmwareDir/$firmwareName"
$shaFile = Invoke-SshCapture -SshArgs $sshBaseArgs -HostSpec "$piUser@$piHost" -RemoteCommand "sha256sum '$remoteFile' | cut -c1-64"
$shaFile = $shaFile.Trim()

$shaHttp = Invoke-SshCapture -SshArgs $sshBaseArgs -HostSpec "$piUser@$piHost" -RemoteCommand "curl -fsS --connect-timeout 3 --max-time 10 '$url' | sha256sum | cut -c1-64"
$shaHttp = $shaHttp.Trim()

if (-not $shaFile -or -not $shaHttp) { throw "SHA check failed (empty hash). shaFile='$shaFile' shaHttp='$shaHttp'" }
if ($shaFile -ne $shaHttp) { throw "HTTP server is NOT serving the uploaded firmware! ($shaFile != $shaHttp)" }
Write-Host "== HTTP firmware matches uploaded file =="

# =====================
# TRIGGER OTA (PI PUBLISHER)
# =====================
Write-Host "== Triggering OTA on $cmdNode/cmd =="

$remotePublisher = "/home/rudyy/er1/scripts/ota_publish.py"
$remoteCmd = @(
    "python3", $remotePublisher,
    "--dev", $Dev,
    "--cmd-node", $cmdNode,
    "--http-host", $httpHost,
    "--version", $otaVersion,
    "--build", $otaBuild,
    "--target", $Dev,
    "--firmware-name", $firmwareName
) -join " "

$publisherOut = Invoke-SshCapture -SshArgs $sshBaseArgs -HostSpec "$piUser@$piHost" -RemoteCommand $remoteCmd
if ($LASTEXITCODE -ne 0) {
    Write-Host $publisherOut
    throw "ota_publish.py failed"
}

# Keep parseable lines
Write-Host "Firmware : $piFirmwareDir/$firmwareName"
Write-Host "URL      : $url"
Write-Host "Dev      : $Dev"
Write-Host "Version  : $otaVersion"
Write-Host "Build    : $otaBuild"
Write-Host "Target   : $Dev"
Write-Host "CmdNode  : $cmdNode"
Write-Host "CmdTopic : $cmdNode/cmd"
Write-Host "== DONE. Device will update. =="

# =====================
# VERIFY (ON PI) — cannot hang forever
# =====================
$timeoutSec = 25
Write-Host ("== Verifier(Pi): expecting hb.build={0}; watching '{1}/hb' + '{1}/ota' (up to {2}s) ==" -f $otaBuild, $cmdNode, $timeoutSec)

# Run mosquitto_sub ON THE PI (broker is there). -W sets a read-timeout so it cannot hang.
# Parse for:
#  - st=OTA_FAIL -> fail immediately
#  - hb.build == expected -> success
# If the device rolls back (your current problem), this will fail after timeout with a clear message.
$nodeLit   = $cmdNode
$expectLit = $otaBuild
$pyVerify = @'
import json, subprocess, time, sys, re

node = "__NODE__"
expect = "__EXPECT__"
timeout = int(__TIMEOUT__)

topics = [f"{node}/hb", f"{node}/ota", f"{node}/log"]
cmd = ["mosquitto_sub","-h","127.0.0.1","-v","-W","2"]
for t in topics:
    cmd += ["-t", t]

p = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)
start = time.time()

try:
    while True:
        if time.time() - start > timeout:
            print(f"== OTA VERIFY: FAIL (timeout; hb.build never became {expect}) within {timeout}s ==")
            sys.exit(2)

        line = p.stdout.readline()
        if not line:
            continue
        line = line.strip()
        if not line:
            continue
        print(line)

        m = re.match(r"^(\S+)\s+(.*)$", line)
        if not m:
            continue
        topic, payload = m.group(1), m.group(2)

        if topic.endswith("/ota"):
            try:
                o = json.loads(payload)
            except Exception:
                continue
            if o.get("st") == "OTA_FAIL":
                print("== OTA VERIFY: FAIL (device reported OTA_FAIL) ==")
                sys.exit(3)

        if topic.endswith("/hb"):
            try:
                hb = json.loads(payload)
            except Exception:
                continue
            b = hb.get("build")
            if b == expect:
                print("== OTA VERIFY: OK (hb.build matched) ==")
                sys.exit(0)
finally:
    try:
        p.kill()
    except Exception:
        pass
'@

# Inject values safely (avoid PowerShell interpolation issues)
$pyVerify = $pyVerify.Replace("__NODE__", $cmdNode).Replace("__EXPECT__", $otaBuild).Replace("__TIMEOUT__", "$timeoutSec")


# Write python to a temp file on the Pi and run it (avoids horrible quoting issues)
$remotePy = "/tmp/er1_ota_verify.py"
# Use a single-quoted heredoc on the Pi to avoid shell interpolation. IMPORTANT: use real newlines (`n), not "\n".
$pushPy = "cat > '$remotePy' <<'EOF'`n$pyVerify`nEOF"
$null = & ssh @sshBaseArgs "$piUser@$piHost" $pushPy
if ($LASTEXITCODE -ne 0) { throw "Failed to upload verifier script to Pi" }

$verifyOut = & ssh @sshBaseArgs "$piUser@$piHost" "python3 '$remotePy'"
Write-Host ($verifyOut | Out-String).Trim()
if ($LASTEXITCODE -ne 0) {
    throw "== OTA VERIFY: FAIL (hb.build didn't match) within ${timeoutSec}s =="
}
} finally {
    Pop-Location
}
