; ===================== GLOBAL SETTINGS =====================
[platformio]
default_envs = maglock
src_dir      = src
include_dir  = include

; ===================== BASE ENV (SHARED) =====================
[env]
platform      = espressif32
board         = esp32dev
framework     = arduino
monitor_speed = 115200
upload_speed  = 115200

monitor_filters =
    esp32_exception_decoder
    time

build_unflags = -std=gnu++11

build_flags =
    -std=gnu++17
    -D ETH_SPI_HOST=VSPI
    -D ETH_MISO=19
    -D ETH_MOSI=23
    -D ETH_SCLK=18
    -D ETH_CS=15
    -D ETH_RST=27
    -D ETH_SPI_CLOCK_MHZ=20
    ; --- Common project flags ---
    -D PIO_FRAMEWORK_ARDUINO_LWIP2_LOW_MEMORY
    -D ARDUINOJSON_USE_LONG_LONG=1
    -D OTA_PSK=\"${sysenv.OTA_PSK}\"

lib_deps =
    arduino-libraries/Ethernet
    knolleary/PubSubClient
    bblanchon/ArduinoJson


; ===================== CONTROLLER – MAGLOCK =======================
[env:maglock]
extends           = env
build_src_filter  = +<maglock_main.cpp> +<ctrl/**> -<riddles/**>

; ===================== PIANO / IMAGES_PIANO ====================
[env:images_piano]
extends           = env
build_src_filter  = +<images_piano_main.cpp> +<ctrl/**> -<riddles/**> +<riddles/images_riddle.cpp> +<riddles/piano_riddle_fsm.cpp> +<riddles/piano_mapper.cpp>

; ===================== CHESS  =======================
[env:chess]
extends           = env
build_src_filter  = +<chess_main.cpp> +<ctrl/**> -<riddles/**> +<riddles/chess_riddle.cpp>

; ===================== CHESS RFID =======================
[env:chess_rfid]
extends           = env
build_src_filter  = +<chess_rfid_main.cpp> +<ctrl/**> -<riddles/**>
lib_deps =
    ${env.lib_deps}
    miguelbalboa/MFRC522

; ===================== STAR SLIDER LIGHTS ===============
[env:star_slider]
extends           = env
build_src_filter  = +<star_slider_main.cpp> +<ctrl/**> -<riddles/**> +<riddles/star_slider_riddle.cpp>
lib_deps =
    ${env.lib_deps}
    miguelbalboa/MFRC522

; ===================== STAR SKY VERIFY ==================
[env:star_sky]
extends           = env
build_src_filter  = +<star_sky_main.cpp> +<ctrl/**> -<riddles/**> +<riddles/star_sky_riddle.cpp>

; ===================== CANDLE (SOUND) ====================
[env:candles]
extends           = env
build_src_filter  = +<candles_main.cpp> +<ctrl/**> -<riddles/**> +<riddles/candles_riddle.cpp>

; ===================== KNOCKING ==========================
[env:knocking]
extends           = env
build_src_filter  = +<knocking_main.cpp> +<ctrl/**> -<riddles/**> +<riddles/knocking_riddle.cpp>
lib_deps =
    ${env.lib_deps}
    dfrobot/DFRobotDFPlayerMini @ ^1.0.6

; ===================== STOP TIMER ========================
[env:stop_timer]
extends           = env
build_src_filter  = +<stop_timer_main.cpp> +<ctrl/**> -<riddles/**> +<riddles/stop_timer_riddle.cpp>
